{% set name = "apswutils" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apswutils-{{ version }}.tar.gz
  sha256: 4c576b259d708a0f72cdced92565e4f78309913d2082dbe3c9bf653142ddbe58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - pip
  run:
    - python >={{ python_min }}
    - fastcore
    - apsw

test:
  imports:
    - apswutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AnswerDotAI/apswutils
  summary: A fork of sqlite-minutils for apsw
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
